# golangci-lint configuration
# Goal: Maintain Go Report Card grade of A+
# https://goreportcard.com/

version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    # Disabled due to Go 1.21 compatibility or false positives
    - exhaustruct    # Too strict for initialization
    - ireturn        # Interfaces are acceptable return types
    - varnamelen     # Short names are idiomatic in Go
    - wrapcheck      # Too noisy for error wrapping
    - nlreturn       # Formatting preference
    - wsl            # Whitespace linting too opinionated
    - testpackage    # Allow testing internal functions
    - paralleltest   # Not always needed
    - tparallel      # Not always needed

linters-settings:
  # gocyclo checks cyclomatic complexity
  gocyclo:
    min-complexity: 15

  # govet checks for suspicious constructs
  govet:
    enable-all: true
    check-shadowing: true

  # misspell checks for spelling errors
  misspell:
    locale: US
    ignore-words:
      - cicada

  # errcheck checks for unchecked errors
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (*database/sql.Rows).Close

  # gosec checks for security problems
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Errors that are audited elsewhere

  # revive replaces golint
  revive:
    severity: warning
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  # gofmt checks formatting
  gofmt:
    simplify: true

  # goimports checks imports
  goimports:
    local-prefixes: github.com/scttfrdmn/cicada

  # gocritic provides many checks
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - whyNoLint  # We document lint exclusions where needed

  # godot checks comment punctuation
  godot:
    scope: declarations
    capital: true

  # lll checks line length
  lll:
    line-length: 120
    tab-width: 4

  # funlen checks function length
  funlen:
    lines: 100
    statements: 50

  # gci controls import grouping
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/scttfrdmn/cicada)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some issues for test files
  exclude-rules:
    # Ignore errcheck for defer Close() statements
    - text: "Error return value.*Close.*not checked"
      linters:
        - errcheck
    # Ignore errcheck for cleanup functions
    - text: "Error return value.*RemoveAll.*not checked"
      linters:
        - errcheck

    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
        - gosec
        - lll
        - errcheck

    # Allow embedding for table-driven tests
    - path: _test\.go
      text: "embedding"
      linters:
        - govet

    # Exclude specific directories
    - path: internal/testutil
      linters:
        - gochecknoglobals
        - gochecknoinits

  # Show all issues
  exclude-dirs-use-default: false
